# Generated by Django 3.1.5 on 2021-02-17 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semiuscrumy', '0002_auto_20210204_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goalstatus',
            old_name='scrumy_name',
            new_name='status_name',
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goalstatus', to='semiuscrumy.goalstatus'),
        ),
    ]
