# Generated by Django 3.1.5 on 2021-02-03 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrumy_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_id', models.IntegerField(default=1)),
                ('goal_name', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=200)),
                ('moved_by', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('goal_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='semiuscrumy.goalstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrumygoals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=200)),
                ('moved_by', models.CharField(max_length=200)),
                ('moved_from', models.CharField(max_length=200)),
                ('moved_to', models.CharField(max_length=200)),
                ('time_of_action', models.CharField(max_length=200)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='semiuscrumy.scrumygoals')),
            ],
        ),
    ]
